version: '3'
services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: ./
      dockerfile: ./docker-files/Dockerfile
    tty: true
    #privileged: true
    volumes:
      - $PWD:/app/
    environment:
      - IP=${IP}
    ports:
      - 3000:3000